# Generated by Django 5.2.14 on 2026-05-20 10:24

from django.db import migrations, models
import django.db.models.deletion


def populate_iso_code_4217(apps, schema_editor):
    Country = apps.get_model("geo", "Country")
    Country.objects.filter(iso_code_4217="").update(iso_code_4217=models.F("iso_code3"))


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_migration"),
        ("geo", "0006_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="iso_code_4217",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.RunPython(populate_iso_code_4217, migrations.RunPython.noop),
        migrations.AddField(
            model_name="country",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="The currency used in this country",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="countries",
                to="core.currency",
                verbose_name="Currency",
            ),
        ),
    ]
