# Generated by Django 5.2.14 on 2026-05-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_migration"),
        ("geo", "0006_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="The currency used in this country",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="countries",
                to="core.currency",
                verbose_name="Currency",
            ),
        ),
    ]
